<?php
// ...existing code...
class Kernel extends \Illuminate\Foundation\Http\Kernel
{
    // ...existing code...
    protected $routeMiddleware = [
        // ...existing code...
        'role' => \Spatie\Permission\Middleware\RoleMiddleware::class,
        'permission' => \Spatie\Permission\Middleware\PermissionMiddleware::class,
        'role_or_permission' => \Spatie\Permission\Middleware\RoleOrPermissionMiddleware::class,
    ];
    // ...existing code...
}
// ...existing code...