name: Laravel CI/CD to UAT

on:
  push:
    branches: [uat] # atau 'master' tergantung nama branch
  pull_request:
    branches: [uat]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

  #  services:
  #    mysql:
  #      image: mysql:8
  #      env:
  #        MYSQL_ROOT_PASSWORD: root
  #        MYSQL_DATABASE: dblab_booking
  #      ports:
  #        - 3306:3306
  #      options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

   
  laravel-deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
 